# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: engportalapi
  namespace: kube-system
  labels:
    app: engportalapi
spec:
  selector:
    matchLabels:
      app: engportalapi
  replicas: 2
  template:
    metadata:
      labels:
        app: engportalapi
    spec:
      containers:
        - name: engportalapi
          image: portalapicontainer.azurecr.io/portalapi:${GITHUB_SHA}
          ports:
          - containerPort: 5000
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 500m
          env:
          - name: FLASK_APP
            valueFrom:
              secretKeyRef:
                name: portalapisecret
                key: FLASK_APP
          - name: FLASK_DEBUG
            valueFrom:
              secretKeyRef:
                name: portalapisecret
                key: FLASK_DEBUG
          - name: MONGODBASE_CONN_STRING
            valueFrom:
              secretKeyRef:
                name: portalapisecret
                key: MONGODBASE_CONN_STRING
          - name: MONGODBASE
            valueFrom:
              secretKeyRef:
                name: portalapisecret
                key: MONGODBASE
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: portalapisecret
                key: SECRET_KEY
          - name: SERVICE_PRINCIPLE_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: portalapisecret
                key: SERVICE_PRINCIPLE_CLIENT_SECRET
          - name: DOCKER_SERVER_USR
            valueFrom:
              secretKeyRef:
                name: portalapisecret
                key: DOCKER_SERVER_USR
          - name: DOCKER_SERVER_PWD
            valueFrom:
              secretKeyRef:
                name: portalapisecret
                key: DOCKER_SERVER_PWD
          - name: WEBSITES_PORT
            valueFrom:
              secretKeyRef:
                name: portalapisecret
                key: WEBSITES_PORT
          - name: ARM_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: portalapisecret
                key: ARM_CLIENT_ID
          - name: ARM_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: portalapisecret
                key: ARM_CLIENT_SECRET
          - name: ARM_TENANT_ID
            valueFrom:
              secretKeyRef:
                name: portalapisecret
                key: ARM_TENANT_ID
          - name: ARM_SUBSCRIPTION_ID
            valueFrom:
              secretKeyRef:
                name: portalapisecret
                key: ARM_SUBSCRIPTION_ID
          - name: AZURE_WEBHOOK_URL
            valueFrom:
              secretKeyRef:
                name: portalapisecret
                key: AZURE_WEBHOOK_URL
          - name: GITHUB_OAUTH_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: portalapisecret
                key: GITHUB_OAUTH_CLIENT_ID
          - name: GITHUB_OAUTH_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: portalapisecret
                key: GITHUB_OAUTH_CLIENT_SECRET
          - name: TRELLO_API_KEY
            valueFrom:
              secretKeyRef:
                name: portalapisecret
                key: TRELLO_API_KEY
          - name: TRELLO_API_TOKEN
            valueFrom:
              secretKeyRef:
                name: portalapisecret
                key: TRELLO_API_TOKEN
          - name: TRELLO_API_SECRET
            valueFrom:
              secretKeyRef:
                name: portalapisecret
                key: TRELLO_API_SECRET
          - name: TRELLO_TODO_LIST_ID
            valueFrom:
              secretKeyRef:
                name: portalapisecret
                key: TRELLO_TODO_LIST_ID




