apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: engportalapi-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: engportalapi
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 300  # Wait 5 minutes before scaling up based on past metrics
      policies:
        - type: Percent
          value: 100                    # Allow doubling of replicas
          periodSeconds: 10            # Allow scaling every 10 seconds
    scaleDown:
      stabilizationWindowSeconds: 300  # Also use 5-minute window for scaling down
      policies:
        - type: Percent
          value: 100                    # Allow cutting replicas in half
          periodSeconds: 60            # Allow scaling every 60 seconds
