name: Continuous Integration
# do not trigger workflow on change to readme.md only.
on: 
    pull_request:
        types: 
            - opened
        paths-ignore:
            - 'README.md'
    push:
        paths-ignore:
            - 'README.md'
jobs:
    build:
        name: Build and test
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - run: docker build --target test --tag portalapi:test .
        - run: docker run scan --entrypoint poetry portalapi:test
#        - run: docker run --entrypoint poetry portalapi:test run safety check
        - run: docker run portalapi:test

