name: Continuous Integration and Delivery / Deployment
# do not trigger workflow on change to readme.md only.
on: 
    pull_request:
        types: 
            - opened
        paths-ignore:
            - 'README.md'
    push:
        paths-ignore:
            - 'README.md'
jobs:
    build:
        name: Build and test
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - run: docker build --target test --tag portalapi:test .
          - name: Run Trivy vulnerability scanner
            uses: aquasecurity/trivy-action@0.28.0
            with:
#              image-ref: 'docker.io/my-organization/my-app:${{ github.sha }}'
              image-ref: 'docker.io/library/portalapi:test'
              format: 'table'
              exit-code: '0'
#              exit-code: '1'
              ignore-unfixed: true
              vuln-type: 'os,library'
#              severity: 'CRITICAL,HIGH'
              severity: 'CRITICAL'
#        - run: docker scan portalapi:test
          - run: docker run --entrypoint poetry portalapi:test run safety check
            continue-on-error: true
          - run: docker run portalapi:test

    publish:
        name: Publish
        runs-on: ubuntu-latest
        needs: build
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        steps:
          - run: echo Publishing to Azure!
          -
            name: Login to Azure Container Portal
# Login to ACR using Admin account and access token stored within ACR.
# Secrets stored within Github Actions Secrets repository.`
            uses: azure/docker-login@v2
            with:
                login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
                username: ${{ secrets.REGISTRY_USERNAME }}
                password: ${{ secrets.REGISTRY_PASSWORD }}     
          -
            name: Build and Push Production to Azure Container Portal
            uses: actions/checkout@v4
          - run: docker build --target production --tag portalapicontainer.azurecr.io/portalapi:latest .
          - run: docker push portalapicontainer.azurecr.io/portalapi:latest
  # Trigger Terraform to build Azrue IaC. 
          - run: echo Terraform to build Azure Iac
          - name: Azure login
            uses: azure/login@v2
            with:
              creds: ${{ secrets.AZURE_CREDENTIALS }}
    
          -
            name: Terraform
            uses: hashicorp/setup-terraform@v3
  #          with:
  #            client-id: ${{ secrets.ARM_CLIENT_ID }}
  #            subscription_id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  #            tenant_id: ${{ secrets.ARM_TENANT_ID }} 
  #            client_secret: ${{ secrets.ARM_CLIENT_SECRET }}
          - run: terraform init
          - run: terraform apply -auto-approve -lock=false
            env:
              TF_VAR_SERVICE_PRINCIPLE_CLIENT_SECRET: ${{ secrets.TF_VAR_SERVICE_PRINCIPLE_CLIENT_SECRET }}
              TF_VAR_DOCKER_SERVER_USR: ${{ secrets.TF_VAR_DOCKER_SERVER_USR }}
              TF_VAR_DOCKER_SERVER_PWD: ${{ secrets.TF_VAR_DOCKER_SERVER_PWD }}
              TF_VAR_MONGODBASE_CONN_STRING: ${{ secrets.TF_VAR_MONGODBASE_CONN_STRING }}
              TF_VAR_MONGODBASE: ${{ secrets.TF_VAR_MONGODBASE }}
              TF_VAR_FLASK_APP: ${{ variables.FLASK_APP }}
              TF_VAR_FLASK_DEBUG: ${{ variables.FLASK_DEBUG }}
              TF_VAR_SECRET_KEY: ${{ variables.SECRET_KEY }}
              TF_VAR_WEBSITES_PORT: ${{ variables.WEBSITES_PORT }}
          - run: curl -dH -X POST "$(terraform output -raw webhook_url)"


